# coding:utf-8
from Airport.msgQueue.Autosendlk import *
from Airport.test_预安检人票验证 import *
from Airport.test_预安检口人脸验证 import api_v1_face_pre_security_check
from Airport.test_安检口 import api_v1_face_security_check

if __name__ == '__main__':
    lk_date = produce_flight_date()
    while True:
        # 开始发送旅客信息（航班值机信息） 模拟安检系统
        send_lkxx(lk_bdno="780",  # 生成随机的101-999的序列号
                  lk_cardid="410900197211269910",  # 生成随机的正确的身份证号码
                  lk_chkt=get_flight_out_time(),  # 在当前时间上加上对应的延迟时间作为起飞时间
                  lk_cname="申皓",  # 生成人员姓名
                  lk_date=lk_date,  # 以当前时间生成航班日期
                  lk_desk=get_lk_desk(),  # 随机生成正确的航班目的地
                  lk_flight="MK001",  # 累加生成航班号码
                  lk_id=get_time_stamp(),  # 累加生成旅客id
                  lk_inf="INF",  # 是否带婴儿
                  lk_insur="0",  # 设置是否购买保险 设置是否购买保险 随机数
                  lk_sex="1",  # 随机性别
                  lk_vip="1"  # 随机贵宾是否是贵宾 0不是  1是  2未知
                  )
        # 验票需要的参数  比对lk_flight 和 li_date
        time.sleep(0.5)
        body_data = {"reqId": get_uuid(),
                     "flightNo": "MK001",
                     "flightDay": str(lk_date[6:8]),
                     "QTCode": "abcde",
                     "seatId": "1",
                     "startPort": "HET",
                     "boardingNumber": "780"}
        # 发送请求进行验票
        ticket_check(body_data)
        features_1_1 = "VBjfPdSmUT0AAAAAAAAAAAAAAABySvk9bhwfPgAAAAAAAAAAAAAAADSTSj3+5Rc+AAAAAAAAAAD4LWk9wGxYPAAAAACCVwo+AAAAAHR8Ez7KAiw+AN9POrCGYjwAAAAAQN5IPEi9qT0AAAAAAAAAAAAAAACscNU90K8ePQAAAADQr808OtN3PQAAAAAAAAAAvF8NPqB+OzsAAAAAlg7dPQAAAABs7lk+0Jo8Pe7SjT4AAAAAeJ60PQAAAACIXus88PqHPAAAAAAAAAAAtEBGPrCDyD061GY9AAAAAIyxuzwAAAAAmm4cPibfoj0AAAAA0NuEPQAAAAAAAAAAUPukPejGMz0AAAAAUA62PKLC3D24+m08QpJ9PUDJNjza+9c9AAAAAHjdzzwAAAAAVPpoPbB/oT2Uyak8AAAAAJShUz7ecb490IcMPQClRz2AZf89AAAAAArR/T1Ie3M9ca6mPdBhLz0AAAAAIBD+PJqLiD5uI5Q9AAAAAAAAAABA7Ao8YNlhPIQY8D0AAAAAtDD5PAAAAAB1WTs+AAAAAHjXGz0AAAAAyP5JPYCvbDxA7D07eo/KPX41zz0AAAAAMLz4PGA8kzsAAAAAmLjhPeLatD0gS1s9AAAAAAAAAACQ7GM8AAAAAFy+Hj0AAAAAdtBoPljcGT3cyZU8AAAAAAAAAAAopoo9YNPJPAAAAAAAAAAAgxmaPQAAAACQNTE9L5onPgAAAAAAAAAAAAAAAMAB9DwSsgY+qx5mPgAAAAAAAAAAAAAAABsUNz4AAAAAAAAAAAAAAAAAAAAAAAAAAKRmPz74gjc+5v8DPjv5Gz6i804+JSBjPgAAAACwXro8k6NBPtipFD0AAAAAAAAAAAAAAAAAAAAAEABbPQAAAADCDYs9AAAAAN5lCD5wjYE9AAAAAAAAAACIiVY8AAAAAPhIljwAAAAAAAAAAKB8uTtIItQ8AAAAAAAAAABV9wk+lddkPnhhVzzAUQo7AAAAABjtdz0AAAAA7NUZPgAAAAAGj6s9+AmQPQAAAAA+T6Y9vTKRPQAAAAA4TEU9AAAAAAAAAAAAAAAA0Dk5PAAAAADUZi09kBDkPOiCAj0AAAAAAAAAAGjN5T3Aeso9mH9OPQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIC6dzsyYII9ySCTPQAAAACxExs+AAAAAAAAAAAciAw94NpXPQAAAADgakI9AAAAAMiX3Txdues9AAAAAKdcAD4uLSc+fp73PQAAAABYnJA9AAAAAETpPT0AAAAAAAAAAAAAAACI55Q9AAAAAAAAAAAAAAAAppIBPgAAAABQONk8AAAAAAAAAAAAAAAAAAAAAEA4FjsAAAAAAAAAAJAoaj0AAAAA4J1sO2uJGj4AAAAAAAAAAJqooT0AAAAAws+zPWkw7D2muoA+AAAAAG13TT4AAAAAGKecPE6SZT5Mokw+AAAAAOBvrjwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACCfgc+WpjhPcd/Wj4AAAAAAAAAAAAAAAAAAAAAwTtFPgAAAAAAAAAAAAAAAHPGeD5M/989AAAAAHWSGT4Ie0s87pSDPQAAAAAgCIg9AAAAAAAAAAAiVAw9ECjuPUbKaj4AAAAAAAAAAAAAAAB424o8GBSGPWRVkT49xBA+AAAAAEg9aT0AAAAALiIWPVgVZTywo8A8OOoTPQAAAAApVw8+AAAAAGDdCjwAAAAAgEMMPI1rAz4UxaA9lAcJPXx9FD3S9Q8+xNQGPSQmTz4AAAAAsJSIPHA0tDs8ecc8AAAAAJAJGT7qwe09AAAAAKDW3jsAAAAAYDCIPQAAAAAEuUc9AI2NPQAAAADQmIQ+AAAAAAAAAAAAAAAAgE9OPUwSXT0AAAAA6KD9PPXksT0u8QM+Ga4YPjRQHj29Azs+/rohPgAAAACUYoI8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAFoGmj3khNw9AAAAAAAAAAAAAAAAWAs4PQAAAACJIqo9AAAAAAAAAAAAAAAAAAAAAKFQRT4oin49AAAAAAAAAABsIJA9llCpPUu+wj1gCXk9AAAAAIDF3D1Upn49AAAAAOiLyT0AAAAAyCYePQAAAABuIqY9AAAAABpCkj3e8Ro+AAAAAAAAAAAm5f89AAAAAAAAAAAAaHo8JCeLPKCNwjsAAAAA/HrSPSDFFDwAAAAAAAAAAAAAAAAAAAAAQdUKPgAAAAA4q008w+8KPgAAAAAAAAAAAAAAAAAAAADEEiE9AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAOE0mPQAAAAAGnVg9iTw/PgWQez6+F6g9aoPnPYB3OzsceWM9yDjUPAAAAAAAAAAAsFA1PAAAAAAAAAAAloXWPQAAAAAAAAAAAAAAAGwbjj2eJ3Y+AAAAAFSCqTzGezY9EJwTPAAAAAAAAAAAAAAAANh8xzwAAAAAH5n6Pfxx7T2gOrI9AAAAAAAAAAAAAAAAAAAAAAAAAACWrIg9IO5tO4Beqzwc1fU8AAAAAAAAAAAAAAAAAAAAAGiC3DyQfQc8AAAAAPoXLj0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjPIT4AAAAAiOMRPRJ5ij0Avos7bLxvPgAAAAAAAAAAPG6CPAAAAACx/Bs+oAX4O/D1+zzu0K89AAAAAJnx8T15z7E9CAANPAAAAABAB2c9AAAAAAAAAACgJh88pPXgPQAAAAAAAAAAsAmYPc8PtD0AAAAAAAAAAHCI5zwAAAAAAAAAAAAAAABC3j49wJhLPAAAAAAAAAAASXKFPu4z2j0AAAAAqHh8PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYdBs8AAAAAAAAAAAAAAAAz3kEPpjktj0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO4VhD0AAAAAwB0TPgAAAAAAAAAAKJdfPQAAAABgBW48AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAh1EZPgAAAADUQWk9AAAAAAAAAAAAAAAAUCa6OxSfhj1h3I09TdqRPQAAAAAYLEI9AAAAADJSpT0AAAAAUDDsPAAAAAAAAAAAAAAAAF7K9D3o5rE8oPt2PUqU6T0AAAAAAAAAAMD5HDsMBFc+AAAAAAAAAABw/Rk8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA0PgWPIAJeDsAAAAA/juDPfA1Dz1cLq49ZlfUPbB+ODwAAAAAAAAAAAAAAACwlQ4+YPhAPb3tZD7J98M9YD8ROyzbWT3S1pI9AAAAAAAAAAAA1Bw7mD8qPQAAAACkriI+AAAAAAAAAAAAAAAAAAAAAAAs8TkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwaiw9AAAAAHi1TzzYNCw9jB/dPSBhZjsAAAAA2Fm5PF9ZcT4AAAAAAAAAAKhqOD3PGxY+hAtLPQAAAAB2vo49AAAAAK1SLj6kxBw+JFnHPazANj7Y6yw9AAAAAAxMcz2w4GE9JPhhPWztCD0AAAAAAAAAAKpKaj4AAAAA0L8TPOSZ5j0AAAAAvl82PjTPSj0AAAAA6EYePGtqZD7NfEQ+AAAAAAAAAABMIrY8gAgMPbCzADx2cVE+Dz9rPrwNlD1QdyM+ypIkPaDU0j0AAAAAcJyNPgAAAAD4JZw8AAAAAAAAAACApHI8AAAAAJAHEj4MmqM9OlkDPQAAAADD8Qo+AAAAAAAAAACOo/Y9UNCFPRD3Fz2wuuE8cve3PQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAOcO3BVIT7878o8AAAAAAAAAAAAAAAAAAAAAHC2gzsAAAAARB13PQAAAADCz3Y+AAAAAAAAAAAAAAAA0ITbO3k5IT6UYm89AAAAAJUiiz0AAAAAQC41OwAAAAAGgK89AAAAAAAAAAAg3a877MnIPZgQ9j32Yg0+lFBHPdK6xT0AAAAAAAAAAIBfkzzHpk4+AAAAAOW0Az4AAAAA2vUPPgAAAABZDYc9n8DUPbTnvTzg5Us92rEEPQAAAAAkCqM8bmuVPaFxCz6gyAc9lNJSPQAAAAA1334+AAAAAAAAAAAAAAAAtIs1PTSlET0AAAAAAAAAAAAAAABs/ik9hiqoPbCmJz1yhBI+AAAAAJgqVTwAAAAAAAAAAAAAAAAuNfI9CnCtPeg4Pz4AAAAAiAoAPAAAAADEF0U9AAAAAAAAAABcHjM9nF0YPgAAAACIaUA8AAAAAAAGKjokKBc9iApgPQAAAACSvw8+AAAAAFh0Bz4AAAAAAAAAAAAAAAAAAAAAIAXIO4B05DoAAAAAAAAAAKLlID4AAAAAzXKFPuYpUT4AAAAAli2SPQAAAAAAAAAAAAAAAAAAAAAvxHs+cmXwPQAAAAAlDvE9nWE1PgAAAADuAqs+lnG7PQAAAAByXPU9AAAAAAAAAAAAAAAAAAAAAAAAAAAAlUw86DorPQAAAAAAAAAAACxIOjTdgT4AAAAAAAAAAKqkLj0otFU+vkGvPZyJjD0AAAAAAAAAAGCFtTsAAAAAAAAAAMgZcz4AAAAAAAAAAKxn+TwAAAAAAAAAAATLbD4GOPM9AAAAAFYEoz4AAAAAAAAAAAAAAADG/js9AAAAAAAAAAAAAAAA5CU8PjI6Rz4AAAAAqD6EPgAAAABq9bw9AAAAAEChPT2olXA8AAAAANTQbD0AAAAApQwQPuRkrD3AFrY6+IAGPB4a1z0AC3w+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARmJBPqCiqDyivMo90wcFPgAAAAAAAAAAuM8DPpBBVz0AAAAAuN8VPgDmYzoAAAAAAAAAAAAAAACUr0A+AAAAAJg0BzwAAAAAAAAAAAAAAACQgBk8kIIoPSQ8Ez4AAAAAZAlXPTQ9gj0AAAAAfsqDPQAAAAAAAAAAAAAAAGD2GjsAAAAAXMqxPSjg8TwAAAAAWRlEPgAAAAB0Ht48oAiJOwAAAAAAAAAAAAIyPAVjvD4AAAAAAAAAAAzw+zwAAAAAXCXKPeAc+TwAAAAAAAAAAAAAAABAEvs9AAAAANAwJz0G0gU++AabPAAAAABCLR8+AAAAAADrqzkAAAAAAAAAABCDeDwAAAAAAAAAAMb4Hj4cjTU9AAAAAAAAAAAAAAAAAAAAAOWamj4AAAAAAAAAAFhEkzxFV1A+AAAAAEjsKDwAAAAAAAAAAAAAAAAUORI+CFvoPAAAAAAAAAAA+ABrPQAAAABYjYM8AAAAAPA7uj2wGbU8AAAAAAAAAAC0vZA+KJKzPAAAAAAAcAs5jjunPd0sLT4AAAAAAAAAAPd7AD6ePQc+fmw2PgAAAAAAAAAAjDkJPsod6z20pr48AAAAAFLVjj1ALnE79Av0PFKSJz0AAAAAAAAAAAAAAADGd7o+UEnbPdoggT0AAAAA8AAPPAAAAAAAAAAAAAAAAAAAAAA4zqg8N4hvPgAAAADoOTA9AAAAAAAAAAAAAAAA7OQQPRZ1Qj4AAAAAgKnMO9Vjgj4AAAAAAAAAAAAAAAAAEcw5AAAAABz/QT2Ku2Y+0HQNPUqmHT78oy09jZcgPt4ujT0AAAAAlg2oPQAAAAAgJ3M8AAAAAJ0LET4AAAAAuGTjPQAAAAAAAAAAAAAAAAAAAABAMYE7pG10PQAAAAAACCg9AAAAAPgrHTx0HIU9EO+UPAAAAAAAAAAAnONcPQAAAAAAAAAAwMJSOwAAAAAAAAAAAAAAAAAAAABu/Hk9BB6bPdgejjxY/BI+AAAAAAAAAAAAAAAA2M1QPcCq5jwAAAAAyt7oPUGeKD7SkDo9AAAAAJIDST74F3w8AAAAAHBx0jxA5D09PGddPSAkpD1UixI9IE5KPnRCjj0AAAAAMIfmPAAAAAAAAAAAduIoPgAAAAAAAAAAjLEDPvRVWD2QAEQ8AAAAAJViHD6yoF0+AAAAAAAAAAAAAAAAAAAAAOp5Tj6uj6c94CTUOwAAAACAwKM77DP5PQAAAAAAAAAAWGYfPgAAAAAAAAAA+GtZPSi3JTz0Xi89AAAAAAAAAAAAAAAAAAAAAMCjsTsAAAAAgCqJPQAAAACg5oY7qMGsPAAAAAAAAAAAhiQyPo7xID18IAM++H36PAAAAACcF+A9FgG9PdEbOj5aq8I9CCvhPag72DwAFro75Ft5PgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAANjn+zwAAAAA0OgCPtS84j0AAAAAvv2LPQhltTwAAAAAAAAAAAAAAAAAAAAAwObhOgAAAAC8ncY9AAAAALktBz4AAAAAAAAAAJBvGD3wx7c9AAAAAAAAAAA46SE9AAAAAJDyjTxkxCA9AAAAAAAAAAAYTNs9rcAKPuKYkT0AAAAA4l7LPdqNMz0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABe+DkAAAAAAAAAAChBvzyAC8486jPxPea+rD3yyck9gBAAPQAAAADwpOk8AAAAAFhGGj0AAAAA4A3CPEAEbztofvg8aIafPAAAAAAGKZY9MNspPAAAAAAm4PE9AAAAAAAAAAAAAAAAAAAAAHL8UT0Geos9AAAAAAAAAAAAAAAAIbpKPgAAAAAc0Fk9AAAAACgIFz0AAAAAIaRJPgAAAAAAAAAAAAAAAAAAAAAot8o8AAAAAJAhXjwAAAAAOmKHPo6aiT0AAAAAlPC3PCxz5zwAAAAApAWJPQAAAABZygs+BL+EPQAAAAAAAAAAcOfcOwCDGDzKrbs9AAAAAAAAAAAAAAAAAJQZPPim1jwAAAAAAAAAAAAAAAD7MNo9AAAAAOzbJT0AEjo7l+xJPgAAAACIxg49AAAAAAAAAADsSI09AAAAAGA4qzxIb6w9AAAAAAAAAAAAAAAAAAAAANTJ2T14wbY8sMmnPQAAAAAALh09bWE5PgAAAACDVTw+IJIZPAAAAAD0+x09AAAAAAAAAAAAAAAAAAAAAIw/PT1kWxs98+/7PQAAAABt6/89ICazPFbc6T3WhZA9bT0VPgAAAAAAAAAAAAAAACCYQDwAAAAAAAAAAJyqoTzghFM8AAAAAAAAAAAAAAAAeCTFPAAAAAASzh8+AAAAAAAAAAARrlM+AAAAAOiFFzwAAAAAXAd0PuA4ijvcOQo+mv+DPQAAAAAAAAAAqCePPah4xTycbQg+AAAAAAAAAAC0JkA9AAAAAAAAAAAAAAAA+HmZPU7L3z3+31E9JhoaPgAAAAAAXpc+AAAAAILwEz6KEsA9AAAAACR8DT3+qBE9AAAAAAAAAAAAAAAANBaRPaDv/jsAAAAAptnxPQAAAABhwwo+9NidPahjmzwAAAAAlIeGPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACKlCj0AAAAAAAAAAMTs6T14fGY9MMDRPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDxDzwAAAAAndtAPjR1LD6lAQE+AAAAADLR9z1aZwc9bM1iPUhu1jzCTa89AAAAAKhkWD4AAAAAYNGnO5ofsD20/ag9ePJRPa5Y5D1w50s8AMYyOm0SNT7mkyw9QG4zPZzayT3ov989IPqzOwAAAAB2m2I+AAAAANzivj0AAAAAAAAAANih/zxbYTc+EJl4PPhEmzwAAAAAAAAAAACTcj3IsMw8AL5QPUBl7DsAAAAAAAAAAAAAAAAAAAAAAAAAACAppjwAAAAAAAAAAMwSmz3Ic3I9AAAAAKSTyj04xsU98hgPPdNhqz0AAAAAtkh5Pd+N0T0AAAAAGB2dPQAAAAACG/c9AAAAAAAAAACDQhQ+AAAAAAAAAAAAAAAA1FVbPQAAAACGl/Q9oPJAPQAAAAAAAAAAaZMHPs5EDD1ueyQ+AAAAAAAAAACLAFY+FhY/PgAAAAAAAAAAAMB0OJpduD0AAAAApWEtPsSgjj0AAAAAAAAAALh6KTwAAAAAvHWUPAAN6DxiJdI9AAAAAAAAAADgZew8AAAAANDuSzx0iho9CJO0PAAAAADVTcI9AAAAAAYUJD3wP3c8AAAAAAAAAAAAAAAAAAAAAAAAAAAcF649jMO+PAAAAAAAAAAAAAAAAMrZMT1ESpo8d+u0PUKiBD4AAAAAAAAAAAAAAAAAAAAAAAAAAMwzNj0YxbI8moiMPQAAAAAAAAAAKsqIPQAJDzoAAAAAAAAAAAAU3zq0U2M9AAAAAAAAAADoFn08QmgePfC//D1gOts9dLqFPZkcBT40ydE8SX2ZPQCKoToAAAAAAAAAAAAAAAAAAAAAoCTTPQAAAADC9Ig+PwotPgAAAAAAAAAA+O/dPQj+Yz0S4AA9xNutPQAAAACk90U+0JC1PAAAAAB4p4c9rF+gPQy53z2amTs90M6APAAAAAA+U4E9NIpEPQAAAACyD3g9RMiAPgAAAABwlSQ9AAAAANhbmD4AAAAAjMFqPQAAAAAAAAAAAAAAANBRhD5SYHI+Pmu5Pc7bJD0AAAAAgn6OPdRplz1sIsw9AAAAAAAAAADeka09VOC5PQAAAAAAAAAAhNw8PQAAAADIZso9AAAAAAAAAABQidU8AAAAAI4rmz3Qx389mL/iPQAAAAAAAAAAAAAAAD7s5DwMABY9AAAAABws5zxQEcw72HqvPbPZaD4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABI+C09iBM5PYCWETsAAAAAAAAAAAAAAAAAAAAAluuGPZQAujwJ8UM+AAAAAIi6ST0AAAAAAAAAABgg5jwAAAAAAAAAAAAAAACIgkc9gOmGPAAAAAAAAAAAFL57PgAAAACQwRg8OF/hPAAAAAAI0jU9gC/ZPAAAAAAwWRE9zqEJPgAAAAADNyM+YoxwPvIgnD0AAAAAACCNOgAAAABSa0s+AAAAAEgIQj3AGmA9GLOaPQAAAAAAAAAAAAAAAKxH9jwAAAAAwEivOwAAAAAAAAAAAAAAAMPbTD4AAAAAAAAAAOClijwAAAAAAAAAAAAAAABsWrE96GkQPQAAAACQkqI7AAAAAAAAAACqJ/E9mFAkPeQyAz4AAAAAAAAAAGQjqT2e2uM9KtYCPtji9DxAvcw9iL1xPgAAAAAAAAAAYPTOOwAAAAAAAAAAK8RLPgAAAAB/FDA+SHOPPJoZgz4s/u89AAAAAAAAAAAAjIY7sCL9PICnszoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADotJE8Jj6iPpI2AD3/7Ts+vtIZPuXPJT4AAAAAikEPPQAAAAAAAAAA0ki4PajJOz6Ibqs8SKBpPWBF8z0g4gw9UCtPPAAAAAAAAAAAAAAAAIsGOT4AAAAAILdNPWquYT0AAAAAAAAAAAAAAAAY0kY8AAAAAAAAAAA0X/U9AAAAAAAAAAAAAAAA7MFqPcbL1T1GvCI+sf1wPgAAAABU4ds9AAAAAAAAAADYgGY9AAAAAAAAAADo+I48EIzUPAAAAAAAAAAAdG5oPUBdAD0AAAAA6Ba3PAAAAABUlxU+AAAAAAAAAADQO+48AAAAAKT1Wj0A/qE8AAAAAAAAAAAAAAAAbVYNPgAAAAAgF2s9AAAAAAAAAAAAAAAA/FKwPAAAAABaBLY9aO8gPgAAAAAAAAAAwB3PPYcLaz5uUJY9LG0WPZD/2T0AAAAAzrKHPUSiTz0AAAAAAAAAAEBSijwAAAAAAAAAAFwpxz2kLVI9AAAAAKDT+zsAAAAAeaRWPgAAAACpibc9iToMPsY1gT3gqkw7krk9PURzgjwfVJ0+AAAAAFiuHD0AAAAAAAAAAAAAAAD1zyI+Fgz1PQAAAAAAAAAAECxwPCyfkT4AAAAAAAAAAAAAAACcwj49AAAAACiOWz24wow9AAAAAAAAAAC80Pc9aNcCPk7Niz3CvoY9BiCuPUNFEj5+tZ494EziPQAAAAAAAAAAsJPbO274DT0AAAAAqzsBPmS2VD4AAAAA0CNCPAAAAAAAAAAAAAAAAApC8D0AAAAAAAAAAAAAAABN2ws+AAAAAAAAAAC+Uno+CCBHPQAAAADgKFA9rqgXPrB2kjwAAAAAAAAAAIY90z0AAAAAAAAAAJ0xKT7AbPw8QudFPgAAAACsNzE9hl61PZ5fjz5UUqM9XG67PAAAAAC4bCs9O7LYPQAAAAAAAAAAPDWBPAAAAAAKBcA9BIPyPRzaGD6FAIg9AAAAAKgUvTwAAAAAAAAAAAAAAAA4Lbo9AAAAAHBXPz3SDo09sJw6PcBQTTsAAAAAaCmvPBgGrzygbMM9AAAAAAAAAABAKCA+gDfxPPLukz0WOSI9AAAAAAAAAACsFxQ9CG9nPAAAAAANUP89PNgoPeiZHj0AAAAA6B7fPAAAAAAAAAAAAAAAAEeNnz3cJ8Q9QFKdOyiQrzwAAAAAAAAAABx/sj06ALs+AAAAAJDbvDwAAAAAAAAAACjpIjzwSzA96GOyPJTzrD302C0+AAAAALDSxjwAAAAAnGS/PQAAAABMPRA9wOeHPgAAAAAAAAAAYO7yPMjbLj0skIQ8AAAAAAAAAABamSo+AAAAAADFIj0AAAAAAAAAAECSjzwAAAAAqNy+PAAAAAAQudE8Xgl9Pojt/z0AAAAAAAAAAF7/6j0AAAAA+APvPQAAAAAAAAAAlhwuPgAAAABfWzs+AAAAACyLHD4AAAAAQLqXPeDjOTxA7oI7AAAAAAAAAABcOwI92PhhPAS8xDzoPOI9XIa5PegflzwwD+88uBYQPuh75j3yvOs9AAAAACBU/jsAAAAAYrnaPRrm7T2IlbE8AAAAAAAAAAAQQMw9tKxdPQAAAAAAAAAAAAAAAIajhD0AAAAA2F8wPgAAAACp3T8+AAAAAOImej0AAAAAAAAAAAAAAAAAAAAARC0RPQAAAAAAAAAAcH5nPQAAAAA="
        m1 = to_base64(r"C:\Users\admin\Desktop\申皓 - 副本.jpg")
        # 发送预安检人脸验证
        body_data_a = {"reqId": get_uuid(),
                       "gateNo": "atYA-A",
                       "deviceId": "SB001",
                       "cardType": 0,  # 证件类型 int
                       "idCard": "410900197211269910",
                       "nameZh": "申皓",
                       "nameEn": "englishName",
                       "age": get_age("410900197211269910"),  # int  通过身份证证件号码获取旅客年龄
                       "sex": 1,  # int  获取一致的性别信息
                       "birthDate": get_birthday("410900197211269910"),  # 通过前面生成的身份号码获取生日信息
                       "address": "重庆市智慧杭实验室",
                       "certificateValidity": "%s-20201212" % get_birthday("410900197211269910"),  # 时间yyyymmdd或者长期(起-止)
                       "nationality": "中国",
                       "ethnic": "汉族",
                       "contactWay": "13512134390",
                       "scenePhoto": m1,
                       "sceneFeature": features_1_1,
                       "cardPhoto": m1,
                       "cardFeature": features_1_1,
                       "flightNo": "MK001",
                       "flightDay": str(lk_date[6:8]),
                       "QTCode": "abcde",
                       "seatId": "1",
                       "startPort": "HET",
                       "boardingNumber": "780",
                       "fId": get_uuid()}

        # 发送请求
        api_v1_face_pre_security_check(body_data_a)
        time.sleep(1)
        # 进行安检口1:1
        body_data_b = {"reqId": get_uuid(),
                       "gateNo": "atYA-A",
                       "deviceId": "SB001",
                       "cardType": 0,  # 证件类型 int
                       "idCard": "410900197211269910",
                       "nameZh": "申皓",
                       "nameEn": "englishName",
                       "age": get_age("410900197211269910"),  # int
                       "sex": 1,  # int
                       "birthDate": get_birthday("410900197211269910"),
                       "address": "重庆市智慧杭实验室",
                       "certificateValidity": "%s-20201212" % get_birthday("410900197211269910"),  # 时间yyyymmdd或者长期(起-止)
                       "nationality": "中国",
                       "ethnic": "汉族",
                       "contactWay": "13512134390",
                       "scenePhoto": m1,
                       "sceneFeature": features_1_1,
                       "cardPhoto": m1,
                       "cardFeature": features_1_1}
        # 发送请求
        api_v1_face_security_check(body_data_b)
        time.sleep(1)
        break
    pass
